export const SET_ALL_CUR = 'SET_ALL_CUR'
export const SET_CUR_DATA = 'SET_CUR_DATA'
export const SET_CURRENCY_RATE = 'SET_CURRENCY_RATE'
export const SET_DATE_PERIOD = 'SET_DATE_PERIOD'
export const SET_ERROR = 'SET_ERROR'
export const SET_COUNT_MONTH = 'SET_COUNT_MONTH'

export const INITIALIZED_SUCCESS = 'INITIALIZED_SUCCESS'